language: minimal # setting language to C will override cross-compiler and fail

compiler:
  - gcc

sudo: required

services:
  - docker

env:
  global:
    - USER=tester

cache:
  directories:
    - /usr/local/bin

before_install:
  - docker pull wjliang/openamp:latest

script:
  - ls
